= Deck.js + AsciiDoctor + Gradle
:author: Schalk W. Cronjé
:email: ysb33r@gmail.com


== Title of Slide One 

This is the first slide after the title slide.

== A slide with a block

.Gilb's QA Values
****
Efficiency:: We will always strive to find and implement the most cost effective methods to assure long term system
quality.

Confidence:: Our assertions of confidence in system releases can be relied on totally, and will be very explicit about
caveats, assumptions, maximum deviations, and responsibilities if accepted.

Predictability:: We will develop our ability to predict system attributes based on early indicators
(example: field bugs based on major defects in requirement).

Leanness:: We will constantly remove and avoid all activity that does not have clear measured value contributions in
relation to its real cost.

Perceptiveness:: Even when not directed by our stakeholder to explicitly deal with them, we will anticipate all
critical system quality aspects.

Reality:: we will not be driven by ideals, fads, customs, misunderstandings or illogical arguments.
We will be directed by current local realities: how things work for us now.

Delegation:: Avoiding micromanagement - we will practice extreme delegation for details and choice of design,
and for processes, to the people who do them daily. Management’s role will be limited to setting clear measurable
high level objectives for products and processes, and then enabling their staff to reach them.
****

== A slide with bullet points

* Efficiency
* Confidence
* Predictability
* Leanness
* Perceptiveness
* Reality
* Delegation

== A slide with a table

[cols="2*"]
|===
| item
| cycle time (calendar days)

| 123
| 12

| 124
| 10
|===

